workflows:
  cordova:
    name: Apache Cordova
    environment:
      vars:
        GRADLE_PATH: /Users/builder/programs/gradle-5.6.4/bin
    scripts:
     - sudo npm install -g ionic
     - npm install
     - ionic cordova prepare android
     - PATH=$PATH:$GRADLE_PATH ionic cordova build android
